version: '3.7'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/app/server'
    ports:
      - 5002:5000
    environment:
      - DATABASE_URL=postgresql+psycopg2://${DB_USER}:${DB_PASS}@database:5432/${DB_NAME}
      - SECRET_KEY=${APP_SECRET}
    depends_on:
      - database

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app/client'
      - '/app/client/node_modules'
    ports:
      - 3008:3000
    environment:
      - NODE_ENV=${APP_ENV}:development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - server
      - client