# base image
FROM python:3.7.2-slim

# install netcat
RUN apt-get update && \
  apt-get -y install netcat && \
  apt-get clean

# set working directory
WORKDIR /app/server

# add and install requirements
COPY ./requirements.txt /app/server/requirements.txt
RUN pip install -r requirements.txt

# add app
COPY . /app/server

# run server
CMD python3 -m app